apiVersion: v1
kind: Pod
metadata:
  generateName: a-
  labels:
    app.kubernetes.io/name: "a"
    app.kubernetes.io/component: "scalehist"
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 100m
          memory: 4Gi